language: c
sudo: required
env:
  global:
    - PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH"
matrix:
  include:
    - os: osx
      env: SCHEME=chez
    - os: osx
      env: SCHEME=ikarus
      before_script:
        - brew update
        - brew install libffi
        - brew install bzr
    - os: osx
      env: SCHEME=ironscheme
    - os: linux
      env: SCHEME=chez
      addons:
        apt:
          packages:
            - libncurses5-dev
            - libgmp-dev
            - libffi-dev
    - os: linux
      env: SCHEME=ikarus
      addons:
        apt:
          packages:
            - libncurses5-dev
            - libgmp-dev
            - libffi-dev
    - os: linux
      env: SCHEME=vicare
      addons:
        apt:
          packages:
            - libncurses5-dev
            - libgmp-dev
            - libffi-dev
    - os: linux
      env: SCHEME=ironscheme
#    - os: windows
#      env: SCHEME=chez
#      before_script:
#        - rm .git/index; git reset --hard
#        - choco install make -y
#        - choco install sudo -y
dist: bionic
script:
  - .travis/install_scheme
  - .travis/run_tests
