name: run_haskell_tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GHC with GHCup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh -s -- -y
          ghcup install ghc 9.2.4
          ghcup set ghc 9.2.4

      - name: Setup Haskell with Stack
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '9.2.4'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Install Haskell dependencies
        run: stack setup

      - name: Build project
        run: stack build

      - name: Run tests
        run: stack test

      - name: Clean ressources
        run: |
          rm -f glados
          rm -f glados.cabal
